//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace hesap_makinesi1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableKayit
    {
        public int ID { get; set; }
        public System.DateTime TARIH { get; set; }
        public Nullable<double> SAYI1 { get; set; }
        public Nullable<double> SAYI2 { get; set; }
        public string ISLEM { get; set; }
        public Nullable<double> SONUC { get; set; }
    }
}
